site_name: Utilery
theme: readthedocs
repo_url: https://github.com/etalab/utilery
site_description: Micro vector tile manufacturing from PostGIS.
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuration]
- [api.md, Endpoints]
- [plugins.md, Plugins]
